parameters:
    sms.class:  Brickstorm\SmsBundle\Service\Sms
    sms.transport.class: Brickstorm\SmsBundle\Transport\SmsFactor

services:
    brickstorm.smstransport:
        class:        %sms.transport.class%
    brickstorm.sms:
        class:        %sms.class%
        arguments:    [@brickstorm.smstransport]
